import { supabase } from './lib/supabaseClient.ts';
import { demo } from './lib/demoData.js';
import './styles.css';

let state = { tab:'home', session:null, profile:null, search:'', results:[], login:false, adminVerified:false, quiz:null, answers:{}, started:false, done:false, timed:false, left:0, installPrompt:null };
const root = document.querySelector('#root');

window.addEventListener('beforeinstallprompt', e => { e.preventDefault(); state.installPrompt = e; render(); });
supabase.auth.getSession().then(({data}) => { state.session = data.session; loadProfile(); });
supabase.auth.onAuthStateChange((_event, session) => { state.session = session; loadProfile(); });
async function loadProfile(){ if(!state.session?.user){ state.profile=null; return render(); } const {data}=await supabase.from('profiles').select('id, full_name, role').eq('id',state.session.user.id).single(); state.profile=data; render(); }
function icon(name){return {home:'⌂',quiz:'🏆',library:'📚',admin:'⚙',search:'⌕'}[name]||'•'}
function setTab(tab){ Object.assign(state,{tab,quiz:null,started:false,done:false,answers:{}}); render(); }
async function doSearch(value){ state.search=value; state.results=[]; if(value==='@dmin' && state.session?.user){ const {data}=await supabase.from('profiles').select('role').eq('id',state.session.user.id).single(); if(data?.role==='admin'){state.adminVerified=true; state.tab='admin';} return render(); } if(value && value!=='@dmin'){ const s=value.toLowerCase(); state.results=[...demo.quizzes,...demo.topics,...demo.pyqs,...demo.notes].filter(x=>(x.title||x.name).toLowerCase().includes(s)); } render(); }
async function installApp(){ if(!state.installPrompt) return; state.installPrompt.prompt(); await state.installPrompt.userChoice; state.installPrompt=null; render(); }
function nav(){ return ['home','quiz','library', ...(state.profile?.role==='admin'?['admin']:[])].map(t=>`<button class="${state.tab===t?'active':''}" data-tab="${t}">${icon(t)}<span>${t[0].toUpperCase()+t.slice(1)}</span></button>`).join(''); }
function shell(content){return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="logo">🎓</div><div><b>ExamPrep</b><span>Premium PWA</span></div></div>${nav()}</aside><main class="main"><header class="topbar"><div class="searchbox">${icon('search')}<input id="search" value="${state.search}" placeholder="Search quizzes, topics, PYQs, notes..."/></div><button id="install" class="install">Install App</button>${state.session?'<button id="signout" class="ghost">Sign out</button>':'<button id="loginBtn" class="primary">Login</button>'}</header>${state.results.length?`<section class="panel"><h3>Search results</h3><div class="grid small">${state.results.map(r=>`<div class="card">${r.title||r.name}</div>`).join('')}</div></section>`:''}${content}</main><nav class="bottom">${nav()}</nav>${state.login?loginModal():''}</div>`}
function home(){return `<section class="hero"><div><p class="eyebrow">✨ Ultra-fast student exam app</p><h1>Practice quizzes, download study resources, and install like a native Android app.</h1><p>Guests can attempt quizzes instantly. Students log in only when downloading PYQs or handwritten notes.</p><button class="primary big" data-tab="quiz">Start Practicing</button></div><div class="phone"><div>Score</div><b>92%</b><span>Timed mode ready</span></div></section><section class="grid"><div class="card metric"><span>Quiz Attempts</span><b>12.4k</b></div><div class="card metric"><span>PYQs</span><b>450+</b></div><div class="card metric"><span>Notes</span><b>800+</b></div></section>`}
function quizPage(){ if(!state.quiz) return `<section class="panel"><h2>Class → Subject → Topic → Quiz</h2><div class="grid">${demo.quizzes.map(q=>`<div class="card"><h3>${q.title}</h3><p>${demo.topics.find(t=>t.id===q.topic_id)?.name}</p><button class="primary" data-quiz="${q.id}">Open Quiz</button></div>`).join('')}</div></section>`; const qs=demo.questions.filter(q=>q.quiz_id===state.quiz.id); if(!state.started)return `<section class="panel"><div class="card"><label><input id="timed" type="checkbox" ${state.timed?'checked':''}/> Timed Mode</label><button id="begin" class="primary">Begin</button></div></section>`; const score=qs.filter(q=>state.answers[q.id]===q.correct_option).length; return `<section class="panel">${state.timed?`<p class="timer">⏱ ${state.left}s remaining</p>`:''}${qs.map(q=>`<div class="card"><h3>${q.body}</h3>${q.options.map((o,i)=>`<label class="option"><input ${state.done?'disabled':''} type="radio" name="${q.id}" data-answer="${q.id}:${i}" ${state.answers[q.id]===i?'checked':''}/> ${o}</label>`).join('')}${state.done?`<p class="${state.answers[q.id]===q.correct_option?'ok':'bad'}">${q.explanation}</p>`:''}</div>`).join('')}${state.done?`<div class="result"><h2>${score}/${qs.length} Correct</h2><button data-tab="quiz">Back</button></div>`:`<button id="submit" class="primary">Submit</button>`}</section>`}
function library(){ const cards=[...demo.pyqs.map(p=>[p,`PYQ • ${p.year}`,'pyqs']),...demo.notes.map(n=>[n,'Handwritten Note','notes'])]; return `<section class="panel"><h2>PYQs & Handwritten Notes</h2><div class="grid">${cards.map(([i,l,b])=>`<div class="card"><span>${l}</span><h3>${i.title}</h3><p>${i.downloads} downloads</p><button class="primary" data-download="${b}:${i.file_path}">⬇ Download</button></div>`).join('')}</div></section>`}
function admin(){ if(!state.session||!(state.adminVerified||state.profile?.role==='admin')) return `<section class="panel locked">🛡 Admin access requires verified owner role.</section>`; return `<section class="panel"><h2>Admin Dashboard</h2><div class="grid"><div class="card metric"><span>Total users</span><b>—</b></div><div class="card metric"><span>Quiz attempts</span><b>—</b></div><div class="card metric"><span>Downloads</span><b>—</b></div></div><div class="card"><h3>Content Management</h3><p>CRUD modules for Classes, Subjects, Topics, Quizzes, Questions, PYQs, and Notes are protected by Supabase RLS admin policies.</p><button class="primary">☁ Upload Resource</button></div><small>Server role re-check completed before rendering admin UI.</small></section>`}
function loginModal(){ return `<div class="modal"><div class="modal-card"><h2>Student Login</h2><p>Magic link login unlocks PYQ and notes downloads.</p><input id="email" placeholder="you@example.com"/><button id="magic" class="primary">Send magic link</button><button id="close" class="ghost">Close</button></div></div>` }
function render(){ root.innerHTML=shell(({home,quiz:quizPage,library,admin}[state.tab]||home)()); bind(); }
function bind(){ document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab)); document.querySelector('#search')?.addEventListener('input',e=>doSearch(e.target.value)); document.querySelector('#install')?.addEventListener('click',installApp); document.querySelector('#loginBtn')?.addEventListener('click',()=>{state.login=true;render()}); document.querySelector('#signout')?.addEventListener('click',()=>supabase.auth.signOut()); document.querySelector('#close')?.addEventListener('click',()=>{state.login=false;render()}); document.querySelector('#magic')?.addEventListener('click',async()=>{const email=document.querySelector('#email').value; const {error}=await supabase.auth.signInWithOtp({email}); alert(error?error.message:'Check your email for the magic link.');}); document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{state.quiz=demo.quizzes.find(q=>q.id===b.dataset.quiz);state.left=state.quiz.duration_seconds;render()}); document.querySelector('#timed')?.addEventListener('change',e=>state.timed=e.target.checked); document.querySelector('#begin')?.addEventListener('click',()=>{state.started=true;render(); if(state.timed) tick();}); document.querySelectorAll('[data-answer]').forEach(i=>i.onchange=()=>{const [id,v]=i.dataset.answer.split(':'); state.answers[id]=Number(v);}); document.querySelector('#submit')?.addEventListener('click',()=>{state.done=true;render()}); document.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{if(!state.session){state.login=true;return render()} const [bucket,...path]=b.dataset.download.split(':'); const {data,error}=await supabase.storage.from(bucket).createSignedUrl(path.join(':'),60); if(error) alert(error.message); else window.open(data.signedUrl,'_blank')}); }
function tick(){ if(!state.timed||state.done||!state.started)return; setTimeout(()=>{state.left--; if(state.left<=0){state.done=true;} render(); tick();},1000); }
render();
